version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shiftly_mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Shiftly_Local_123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Shiftly_Local_123!", "-No", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: shiftly_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mssql_data:
